name: ci

on:
  schedule:
    - cron: '00 1 * * *'
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build zsh image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: infrastrukturait/terraform-workshop:latest
          cache-from: type=registry,ref=infrastrukturait/terraform-workshop:latest
          cache-to: type=inline

      -
        name: Build zsh image and push
        uses: docker/build-push-action@v3
        with:
          context: ./bash
          platforms: linux/amd64,linux/arm64
          push: true
          tags: infrastrukturait/terraform-workshop:bash
          cache-from: type=registry,ref=infrastrukturait/terraform-workshop:bash
          cache-to: type=inline
