name: docker-buildx

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - "main"

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: "versions.json"
          prefix: versions

      - name: Build zsh image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            TFDOCS_VERSION=${{ env.versions_tfdocs_version }}
            INFRACOST_VERSION=${{ env.versions_infracost_version }}
            TFENV_VERSION=${{ env.versions_tfenv_version }}
          push: true
          tags: infrastrukturait/terraform-workshop:latest
          cache-from: type=registry,ref=infrastrukturait/terraform-workshop:latest
          cache-to: type=inline

      - name: Build bash image and push
        uses: docker/build-push-action@v3
        with:
          context: ./bash
          platforms: linux/amd64,linux/arm64
          build-args: |
            TFDOCS_VERSION=${{ env.versions_tfdocs_version }}
            INFRACOST_VERSION=${{ env.versions_infracost_version }}
            TFENV_VERSION=${{ env.versions_tfenv_version }}
          push: true
          tags: infrastrukturait/terraform-workshop:bash
          cache-from: type=registry,ref=infrastrukturait/terraform-workshop:bash
          cache-to: type=inline
